package com.prism.springas.utils;

import com.prism.springas.utils.BasePage;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;


import java.util.List;
/*
	数据全查询自动生成配置*/
@Component("baseTableCfg")
public class BaseTableCfg {

	//=>药品信息(DRUGINFO)数据全查询字段
	//=>@YanHaoNan,Mon May 20 14:07:49 CST 2019,原生生成代码
	//=>对应关联表：DRUGINFO,SUPPLIER2,DTINFO1,SYSUSER1
	private String DRUGINFO = "DRUGINFO.ID AS DRUGINFO_ID,DRUGINFO.PHONE AS DRUGINFO_PHONE,DRUGINFO.VERSION AS DRUGINFO_VERSION,DRUGINFO.ISDELETE AS DRUGINFO_ISDELETE,DRUGINFO.DATETIME AS DRUGINFO_DATETIME,DRUGINFO.CREATETIME AS DRUGINFO_CREATETIME,DRUGINFO.NAME AS DRUGINFO_NAME,DRUGINFO.STOCK AS DRUGINFO_STOCK,DRUGINFO.SUPPLIER AS DRUGINFO_SUPPLIER,DRUGINFO.TID AS DRUGINFO_TID,DRUGINFO.UID AS DRUGINFO_UID";

	//=>对应关联表字段：DRUGINFO.SUPPLIER=SUPPLIER2.ID,DRUGINFO.TID=DTINFO1.ID,DRUGINFO.UID=SYSUSER1.ID
	private String DRUGINFO_JOIN = "DRUGINFO.SUPPLIER=SUPPLIER2.ID,DRUGINFO.TID=DTINFO1.ID,DRUGINFO.UID=SYSUSER1.ID";

	public String getDRUGINFO(){	return DRUGINFO; }
	public String getDRUGINFO_JOIN(){	return DRUGINFO_JOIN; }

	public void setDRUGINFO(String  DRUGINFO){	 this.DRUGINFO = DRUGINFO; }
	public void setDRUGINFO_JOIN(String  DRUGINFO_JOIN){	 this.DRUGINFO_JOIN = DRUGINFO_JOIN; }

	//=>药品分类管理信息(DTINFO)数据全查询字段
	//=>@YanHaoNan,Mon May 20 14:07:49 CST 2019,原生生成代码
	//=>对应关联表：DTINFO,SYSUSER1
	private String DTINFO = "DTINFO.ID AS DTINFO_ID,DTINFO.VERSION AS DTINFO_VERSION,DTINFO.ISDELETE AS DTINFO_ISDELETE,DTINFO.DATETIME AS DTINFO_DATETIME,DTINFO.CREATETIME AS DTINFO_CREATETIME,DTINFO.NAME AS DTINFO_NAME,DTINFO.UID AS DTINFO_UID";

	//=>对应关联表字段：DTINFO.UID=SYSUSER1.ID
	private String DTINFO_JOIN = "DTINFO.UID=SYSUSER1.ID";

	public String getDTINFO(){	return DTINFO; }
	public String getDTINFO_JOIN(){	return DTINFO_JOIN; }

	public void setDTINFO(String  DTINFO){	 this.DTINFO = DTINFO; }
	public void setDTINFO_JOIN(String  DTINFO_JOIN){	 this.DTINFO_JOIN = DTINFO_JOIN; }

	//=>Hetara规则引擎表(HETARAENGINE)数据全查询字段
	//=>@YanHaoNan,Mon May 20 14:07:49 CST 2019,原生生成代码
	//=>对应关联表：HETARAENGINE
	private String HETARAENGINE = "HETARAENGINE.ID AS HETARAENGINE_ID,HETARAENGINE.VERSION AS HETARAENGINE_VERSION,HETARAENGINE.ISDELETE AS HETARAENGINE_ISDELETE,HETARAENGINE.DATETIME AS HETARAENGINE_DATETIME,HETARAENGINE.CREATETIME AS HETARAENGINE_CREATETIME,HETARAENGINE.CODE AS HETARAENGINE_CODE,HETARAENGINE.NAME AS HETARAENGINE_NAME,HETARAENGINE.NOTE AS HETARAENGINE_NOTE";

	//=>对应关联表字段：
	private String HETARAENGINE_JOIN = "";

	public String getHETARAENGINE(){	return HETARAENGINE; }
	public String getHETARAENGINE_JOIN(){	return HETARAENGINE_JOIN; }

	public void setHETARAENGINE(String  HETARAENGINE){	 this.HETARAENGINE = HETARAENGINE; }
	public void setHETARAENGINE_JOIN(String  HETARAENGINE_JOIN){	 this.HETARAENGINE_JOIN = HETARAENGINE_JOIN; }

	//=>Hetara规则表(HETARARULES)数据全查询字段
	//=>@YanHaoNan,Mon May 20 14:07:49 CST 2019,原生生成代码
	//=>对应关联表：HETARARULES,HETARAENGINE1,HETARARULES2
	private String HETARARULES = "HETARARULES.ID AS HETARARULES_ID,HETARARULES.VERSION AS HETARARULES_VERSION,HETARARULES.ISDELETE AS HETARARULES_ISDELETE,HETARARULES.DATETIME AS HETARARULES_DATETIME,HETARARULES.CREATETIME AS HETARARULES_CREATETIME,HETARARULES.CODE AS HETARARULES_CODE,HETARARULES.NAME AS HETARARULES_NAME,HETARARULES.SORT AS HETARARULES_SORT,HETARARULES.EID AS HETARARULES_EID,HETARARULES.ISP AS HETARARULES_ISP,HETARARULES.EPS AS HETARARULES_EPS,HETARARULES.TTAG AS HETARARULES_TTAG,HETARARULES.TEXE AS HETARARULES_TEXE,HETARARULES.FTAG AS HETARARULES_FTAG,HETARARULES.FEXE AS HETARARULES_FEXE,HETARARULES.PID AS HETARARULES_PID,HETARARULES.CPTYPE AS HETARARULES_CPTYPE,HETARARULES.ISNECE AS HETARARULES_ISNECE";

	//=>对应关联表字段：HETARARULES.EID=HETARAENGINE1.ID,HETARARULES.PID=HETARARULES2.ID
	private String HETARARULES_JOIN = "HETARARULES.EID=HETARAENGINE1.ID,HETARARULES.PID=HETARARULES2.ID";

	public String getHETARARULES(){	return HETARARULES; }
	public String getHETARARULES_JOIN(){	return HETARARULES_JOIN; }

	public void setHETARARULES(String  HETARARULES){	 this.HETARARULES = HETARARULES; }
	public void setHETARARULES_JOIN(String  HETARARULES_JOIN){	 this.HETARARULES_JOIN = HETARARULES_JOIN; }

	//=>菜单信息管理表(SYSMENU)数据全查询字段
	//=>@YanHaoNan,Mon May 20 14:07:49 CST 2019,原生生成代码
	//=>对应关联表：SYSMENU,SYSMENU1
	private String SYSMENU = "SYSMENU.ID AS SYSMENU_ID,SYSMENU.VERSION AS SYSMENU_VERSION,SYSMENU.ISDELETE AS SYSMENU_ISDELETE,SYSMENU.CREATETIME AS SYSMENU_CREATETIME,SYSMENU.NAME AS SYSMENU_NAME,SYSMENU.CONTENT AS SYSMENU_CONTENT,SYSMENU.ICON AS SYSMENU_ICON,SYSMENU.PID AS SYSMENU_PID,SYSMENU.ISLOCKED AS SYSMENU_ISLOCKED,SYSMENU.CODE AS SYSMENU_CODE,SYSMENU.PATH AS SYSMENU_PATH,SYSMENU.TITLE AS SYSMENU_TITLE,SYSMENU.COMPONENT AS SYSMENU_COMPONENT,SYSMENU.ISPARENT AS SYSMENU_ISPARENT,SYSMENU.SORT AS SYSMENU_SORT,SYSMENU.DATETIME AS SYSMENU_DATETIME";

	//=>对应关联表字段：SYSMENU.PID=SYSMENU1.ID
	private String SYSMENU_JOIN = "SYSMENU.PID=SYSMENU1.ID";

	public String getSYSMENU(){	return SYSMENU; }
	public String getSYSMENU_JOIN(){	return SYSMENU_JOIN; }

	public void setSYSMENU(String  SYSMENU){	 this.SYSMENU = SYSMENU; }
	public void setSYSMENU_JOIN(String  SYSMENU_JOIN){	 this.SYSMENU_JOIN = SYSMENU_JOIN; }

	//=>系统用户表(SYSUSER)数据全查询字段
	//=>@YanHaoNan,Mon May 20 14:07:49 CST 2019,原生生成代码
	//=>对应关联表：SYSUSER,SYSROLE1
	private String SYSUSER = "SYSUSER.ID AS SYSUSER_ID,SYSUSER.VERSION AS SYSUSER_VERSION,SYSUSER.ISDELETE AS SYSUSER_ISDELETE,SYSUSER.DATETIME AS SYSUSER_DATETIME,SYSUSER.CREATETIME AS SYSUSER_CREATETIME,SYSUSER.EMAIL AS SYSUSER_EMAIL,SYSUSER.PASSWORD AS SYSUSER_PASSWORD,SYSUSER.NAME AS SYSUSER_NAME,SYSUSER.RID AS SYSUSER_RID,SYSUSER.PHONE AS SYSUSER_PHONE,SYSUSER.MOBILE AS SYSUSER_MOBILE,SYSUSER.LASTIP AS SYSUSER_LASTIP,SYSUSER.TYPE AS SYSUSER_TYPE,SYSUSER.AVATAR AS SYSUSER_AVATAR,SYSUSER.NOTE AS SYSUSER_NOTE,SYSUSER.OPENID AS SYSUSER_OPENID";

	//=>对应关联表字段：SYSUSER.RID=SYSROLE1.ID
	private String SYSUSER_JOIN = "SYSUSER.RID=SYSROLE1.ID";

	public String getSYSUSER(){	return SYSUSER; }
	public String getSYSUSER_JOIN(){	return SYSUSER_JOIN; }

	public void setSYSUSER(String  SYSUSER){	 this.SYSUSER = SYSUSER; }
	public void setSYSUSER_JOIN(String  SYSUSER_JOIN){	 this.SYSUSER_JOIN = SYSUSER_JOIN; }

	//=>用户权限信息管理表(SYSROLE)数据全查询字段
	//=>@YanHaoNan,Mon May 20 14:07:49 CST 2019,原生生成代码
	//=>对应关联表：SYSROLE,SYSROLE1
	private String SYSROLE = "SYSROLE.ID AS SYSROLE_ID,SYSROLE.VERSION AS SYSROLE_VERSION,SYSROLE.ISDELETE AS SYSROLE_ISDELETE,SYSROLE.DATETIME AS SYSROLE_DATETIME,SYSROLE.CREATETIME AS SYSROLE_CREATETIME,SYSROLE.NAME AS SYSROLE_NAME,SYSROLE.NOTE AS SYSROLE_NOTE,SYSROLE.ICON AS SYSROLE_ICON,SYSROLE.ISLOCK AS SYSROLE_ISLOCK,SYSROLE.PID AS SYSROLE_PID,SYSROLE.ISTOP AS SYSROLE_ISTOP,SYSROLE.SORT AS SYSROLE_SORT";

	//=>对应关联表字段：SYSROLE.PID=SYSROLE1.ID
	private String SYSROLE_JOIN = "SYSROLE.PID=SYSROLE1.ID";

	public String getSYSROLE(){	return SYSROLE; }
	public String getSYSROLE_JOIN(){	return SYSROLE_JOIN; }

	public void setSYSROLE(String  SYSROLE){	 this.SYSROLE = SYSROLE; }
	public void setSYSROLE_JOIN(String  SYSROLE_JOIN){	 this.SYSROLE_JOIN = SYSROLE_JOIN; }

	//=>菜单及权限信息关联表(SYSROLEMENU)数据全查询字段
	//=>@YanHaoNan,Mon May 20 14:07:49 CST 2019,原生生成代码
	//=>对应关联表：SYSROLEMENU,SYSROLE2,SYSMENU1
	private String SYSROLEMENU = "SYSROLEMENU.ID AS SYSROLEMENU_ID,SYSROLEMENU.VERSION AS SYSROLEMENU_VERSION,SYSROLEMENU.ISDELETE AS SYSROLEMENU_ISDELETE,SYSROLEMENU.DATETIME AS SYSROLEMENU_DATETIME,SYSROLEMENU.CREATETIME AS SYSROLEMENU_CREATETIME,SYSROLEMENU.RID AS SYSROLEMENU_RID,SYSROLEMENU.ADDS AS SYSROLEMENU_ADDS,SYSROLEMENU.DEL AS SYSROLEMENU_DEL,SYSROLEMENU.EDIT AS SYSROLEMENU_EDIT,SYSROLEMENU.SEL AS SYSROLEMENU_SEL,SYSROLEMENU.EXPORTS AS SYSROLEMENU_EXPORTS,SYSROLEMENU.SORT AS SYSROLEMENU_SORT,SYSROLEMENU.MID AS SYSROLEMENU_MID";

	//=>对应关联表字段：SYSROLEMENU.RID=SYSROLE2.ID,SYSROLEMENU.MID=SYSMENU1.ID
	private String SYSROLEMENU_JOIN = "SYSROLEMENU.RID=SYSROLE2.ID,SYSROLEMENU.MID=SYSMENU1.ID";

	public String getSYSROLEMENU(){	return SYSROLEMENU; }
	public String getSYSROLEMENU_JOIN(){	return SYSROLEMENU_JOIN; }

	public void setSYSROLEMENU(String  SYSROLEMENU){	 this.SYSROLEMENU = SYSROLEMENU; }
	public void setSYSROLEMENU_JOIN(String  SYSROLEMENU_JOIN){	 this.SYSROLEMENU_JOIN = SYSROLEMENU_JOIN; }

	//=>数据表仓库(TABLEFOLDER)数据全查询字段
	//=>@YanHaoNan,Mon May 20 14:07:49 CST 2019,原生生成代码
	//=>对应关联表：TABLEFOLDER
	private String TABLEFOLDER = "TABLEFOLDER.ID AS TABLEFOLDER_ID,TABLEFOLDER.VERSION AS TABLEFOLDER_VERSION,TABLEFOLDER.ISDELETE AS TABLEFOLDER_ISDELETE,TABLEFOLDER.DATETIME AS TABLEFOLDER_DATETIME,TABLEFOLDER.CREATETIME AS TABLEFOLDER_CREATETIME,TABLEFOLDER.CODE AS TABLEFOLDER_CODE,TABLEFOLDER.NAME AS TABLEFOLDER_NAME,TABLEFOLDER.NOTE AS TABLEFOLDER_NOTE";

	//=>对应关联表字段：
	private String TABLEFOLDER_JOIN = "";

	public String getTABLEFOLDER(){	return TABLEFOLDER; }
	public String getTABLEFOLDER_JOIN(){	return TABLEFOLDER_JOIN; }

	public void setTABLEFOLDER(String  TABLEFOLDER){	 this.TABLEFOLDER = TABLEFOLDER; }
	public void setTABLEFOLDER_JOIN(String  TABLEFOLDER_JOIN){	 this.TABLEFOLDER_JOIN = TABLEFOLDER_JOIN; }

	//=>供应商(SUPPLIER)数据全查询字段
	//=>@YanHaoNan,Mon May 20 14:07:49 CST 2019,原生生成代码
	//=>对应关联表：SUPPLIER,SYSUSER1
	private String SUPPLIER = "SUPPLIER.ID AS SUPPLIER_ID,SUPPLIER.VERSION AS SUPPLIER_VERSION,SUPPLIER.ISDELETE AS SUPPLIER_ISDELETE,SUPPLIER.DATETIME AS SUPPLIER_DATETIME,SUPPLIER.CREATETIME AS SUPPLIER_CREATETIME,SUPPLIER.NAME AS SUPPLIER_NAME,SUPPLIER.UID AS SUPPLIER_UID";

	//=>对应关联表字段：SUPPLIER.UID=SYSUSER1.ID
	private String SUPPLIER_JOIN = "SUPPLIER.UID=SYSUSER1.ID";

	public String getSUPPLIER(){	return SUPPLIER; }
	public String getSUPPLIER_JOIN(){	return SUPPLIER_JOIN; }

	public void setSUPPLIER(String  SUPPLIER){	 this.SUPPLIER = SUPPLIER; }
	public void setSUPPLIER_JOIN(String  SUPPLIER_JOIN){	 this.SUPPLIER_JOIN = SUPPLIER_JOIN; }

	//=>日志记录(LOGINFO)数据全查询字段
	//=>@YanHaoNan,Mon May 20 14:07:49 CST 2019,原生生成代码
	//=>对应关联表：LOGINFO,SYSUSER1
	private String LOGINFO = "LOGINFO.ID AS LOGINFO_ID,LOGINFO.VERSION AS LOGINFO_VERSION,LOGINFO.ISDELETE AS LOGINFO_ISDELETE,LOGINFO.DATETIME AS LOGINFO_DATETIME,LOGINFO.CREATETIME AS LOGINFO_CREATETIME,LOGINFO.LOGS AS LOGINFO_LOGS,LOGINFO.TYPE AS LOGINFO_TYPE,LOGINFO.UID AS LOGINFO_UID";

	//=>对应关联表字段：LOGINFO.UID=SYSUSER1.ID
	private String LOGINFO_JOIN = "LOGINFO.UID=SYSUSER1.ID";

	public String getLOGINFO(){	return LOGINFO; }
	public String getLOGINFO_JOIN(){	return LOGINFO_JOIN; }

	public void setLOGINFO(String  LOGINFO){	 this.LOGINFO = LOGINFO; }
	public void setLOGINFO_JOIN(String  LOGINFO_JOIN){	 this.LOGINFO_JOIN = LOGINFO_JOIN; }

}